### ISSUE TITLE
About the training resources

### ISSUE THREAD

**Issue by terry-r123** [BioinfoMachineLearning/DeepInteract#11]
Hi @amorehead,
I would like to know how long do you need to train on 72 v100 GPUs? And is it 30 or 50 epochs?

Thanks！

**Comment by amorehead** [comment]
@terry-r123, with 72 v100 GPUs, DeepInteract models took around 2 hours to train for approximately 40 epochs each.

**Comment by terry-r123** [comment]
@amorehead,
Thanks very much!

**Comment by terry-r123** [comment]
Hi @amorehead,
What is the batch size with 72 v100 GPUs for around 2 hours?

**Comment by amorehead** [comment]
With this default configuration, the effective batch size is 72.

**Comment by terry-r123** [comment]
> With this default configuration, the effective batch size is 72.

Thanks! I get it!
