### ISSUE TITLE
About positive labels for each inter-chain residue pair

### ISSUE THREAD

**Issue by terry-r123** [BioinfoMachineLearning/DeepInteract#12]
Hi @amorehead, 

I was wondering if the positive labels for the CASP and DB5 datasets are also determined by each inter-chain residue pair that are found within 6 ˚A?

Thanks!

**Comment by amorehead** [comment]
Hi, @terry-r123.

Yes, the positive labels for these datasets used the same labeling scheme, 6 Angstrom inter-chain inter-residue distances.

**Comment by terry-r123** [comment]
> Hi, @terry-r123.
> 
> Yes, the positive labels for these datasets used the same labeling scheme, 6 Angstrom inter-chain inter-residue distances.

Thanks!
