### ISSUE TITLE
what genetic databases did you use?

### ISSUE THREAD

**Issue by onlyonewater** [BioinfoMachineLearning/DeepInteract#13]
Hi, for the DIPS-PLUS dataset, what genetic databases did you use when you generated the DIPS-PLUS dataset from the raw PDB file, and for the casp, and db5 datasets?

**Comment by onlyonewater** [comment]
@amorehead

**Comment by amorehead** [comment]
Hi, @onlyonewater. For sequence-based feature generation, we used the BFD database to build DIPS-Plus, CASP, and DB5.

**Comment by onlyonewater** [comment]
Ok, I get it, thanks!!!
