### ISSUE TITLE
what does this code mean？

### ISSUE THREAD

**Issue by onlyonewater** [BioinfoMachineLearning/DeepInteract#15]
what does this code mean？It seems to be used during data loader.

https://github.com/BioinfoMachineLearning/DeepInteract/blob/c78d205465f02ee4ef751dbbafb7ec8f30c75c9a/project/datasets/DIPS/dips_dgl_dataset.py#L137-L141

**Comment by amorehead** [comment]
Hi, @onlyonewater.

This code allows one to create a separate dataloader dedicated to loading the same input example during training/validation to visualizate model predictions (e.g., visualizing distance matrices or contact maps as 2D images). The reason one may want to do so is to be guaranteed that one can always index into this "visualization" dataloader without running into an out-of-bounds error (achieved by duplicating the same example "n" times). Then, one Line 92 [here](https://github.com/BioinfoMachineLearning/DeepInteract/blob/d0781de9364b7cf932f5013ac2e29e05e9fa4f40/project/datasets/PICP/picp_dgl_data_module.py#L92), you can see where we create this dedicated "visualization" dataloader/dataset.

I hope this clarifies matters.

**Comment by onlyonewater** [comment]
ok, I get it, thanks!!
