### ISSUE TITLE
which pdb files are used in CASP-CAPRI test dataset?

### ISSUE THREAD

**Issue by onlyonewater** [BioinfoMachineLearning/DeepInteract#8]
hi, can you provide the original 19 pdb files for CASP-CAPRI 13 & 14 dataset?

**Comment by amorehead** [comment]
Hi, @onlyonewater. Absolutely. I believe the ZIP archive below should contain the chain splits we ultimately used in this work. If you have any other questions, let me know. Thanks for expressing interest in our work!

[CASP-CAPRI13-14_Chain_Splits.zip](https://github.com/BioinfoMachineLearning/DeepInteract/files/8684064/CASP-CAPRI13-14_Chain_Splits.zip)

**Comment by onlyonewater** [comment]
hi, @amorehead I get it, thanks!!!

**Comment by onlyonewater** [comment]
which the difference between `5w6l_r_u.pdb` and `5w6l_l_u.pdb` files?

**Comment by amorehead** [comment]
Hi, @onlyonewater. These files simply follow a naming scheme similar to that in the Docking Benchmark 5 dataset. For example, `5w6l_r_u.pdb` here would represent the structure of a receptor (e.g., the right chain), while `5w6l_l_u.pdb` would represent the structure of the ligand (e.g., the left chain).

**Comment by onlyonewater** [comment]
so, should I calculate the contact map for these two pdb files separately?

**Comment by amorehead** [comment]
@onlyonewater, the intended use case for these two PDB files is to actually predict a single contact map that represents the _inter-chain_ interactions between their residues. Our inference pipeline should support you specifying two separate PDB files as input, and the output contact map (as a NumPy array) will represent the predicted inter-chain contact probabilities for each pair of residues.

**Comment by onlyonewater** [comment]
oh, I get it, thanks!!
